name: Publish to hex on release

on:
  release:
    types: [published]

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: erlef/setup-beam@v1
        with:
          otp-version: "26.0.2"
          gleam-version: "1.5.1"
          rebar3-version: "3"
      - run: gleam deps download
      - run: gleam pubish -y
        env:
          HEXPM_API_KEY: "${{ secrets.HEXPM_API_KEY }}"
