name: test

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: erlef/setup-beam@v1
        with:
          otp-version: "26.0.2"
          gleam-version: "1.5.1"
          rebar3-version: "3"
          # elixir-version: "1.15.4"
      - run: gleam deps download
      - name: Cache Memcached
        id: cache-memcached
        uses: actions/cache@v4
        with:
          path: memcached
          key: ${{ runner.os }}-memcached

      - name: Build memcached
        if: steps.cache-memcached.outputs.cache-hit != 'true'
        run: |
          sudo apt-get install build-essential libevent-dev
          wget -O memcached.tgz http://memcached.org/latest
          tar xvzf memcached.tgz
          mv memcached-1.* memcached-src
          cd memcached-src
          ./configure --prefix=$PWD/out
          make && make install
          mv out/bin/memcached ..
          cd ..
          rm -r memcached-src
      - name: Start memcached
        run: |
          ./memcached -p 11211 &
          echo "user:pass" > auth
          ./memcached -Y auth -p 11212 &
      - run: gleam test
      - run: gleam format --check src test
